on:
  workflow_dispatch:
 # schedule:
 # - cron: "0 11 * * *"

name: run_elcom

jobs:
  run_forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install deps
        run: |
           sudo apt-get update -y
           sudo apt-get install libnetcdf-dev 
           sudo apt-get install libomp-dev

      - name: Run ELCOM
        run: |
          chmod u+x binary/elcd_20250526
          binary/elcd_20250526  
