on:
  workflow_dispatch:
 # schedule:
 # - cron: "0 11 * * *"

name: run_elcom

jobs:
  run_forecast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install deps
        run: |
           apt-get update
           apt-get install libnetcdf-dev libomp-dev

      - name: Run ELCOM
        run: binary/elcd_20250526  
